### ISSUE TITLE
A disabled test should be an error

### ISSUE THREAD

**Issue by kumar303** [mozilla/eslint-config-amo#159]
This should be `error` not `warn`:

https://github.com/mozilla/eslint-config-amo/blob/82a97e56dfa0d441fbf8a52a3a9b35cc10645e38/index.js#L88

A test gets disabled in jest by adding `skip` to it, like `describe.skip(...)`. I can't think of why anyone would need to commit code like this so it should be an error. This will prevent accidental commits since not everyone reads the lint warnings.

**Comment by willdurand** [comment]
Fixed by ce91c67f3d1019d64b7a99a1c8854dfbc7a98c9a

**Comment by willdurand** [comment]
Release: https://github.com/mozilla/eslint-config-amo/releases/tag/1.21.0
