### ISSUE TITLE
Add semi-colon rules

### ISSUE THREAD

**Issue by kumar303** [mozilla/eslint-config-amo#24]
We always want semi-colons at the end of the line (not the beginning, etc). https://eslint.org/docs/rules/semi

**Comment by muffinresearch** [comment]
I don't think that linked rule can actually control the placement of the semi-colon wrt to the expression unfortunately.

**Comment by kumar303** [comment]
Ah, whoops, I believe we want [`semi-style`](http://eslint.cn/docs/rules/semi-style) with the `last` option.
