### ISSUE TITLE
Allow for... of syntax

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/eslint-config-amo#45]
Based on the comment at https://github.com/mozilla/addons-frontend/pull/4354#discussion_r167308585, we should update the eslint configuration to allow `for... of` syntax.

**Comment by bobsilverberg** [comment]
From what I can tell, the rule that is preventing us from using `for... of` is defined at [1]. I have a couple of questions/comments about this:

1. Is that correct, or am I misunderstanding the dependencies and where our rules come from?

2. Based on an answer posted at [2]  it doesn't seem like there's a way to override a single rule which is defined in a parent's definition of `no-restricted-syntax`. So if we want to allow `for... of` but keep the other three exclusions from the parent file, we have to copy the entire `no-restricted-syntax` into our config and remove the single rule. As long as we're considering doing that, perhaps we should evaluate whether we want to keep the other 3 rules as well. They are:

- ForInStatement
- LabeledStatement
- WithStatement

and they are described via messages also at [1]. At first glance it does look like we may want to keep those restricted, although I'm not sure how important that is.

What do others think about this? Should we just copy those three rules (omitting the rule for`ForOfStatement`) into our own config?

[1] https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L330
[2] https://stackoverflow.com/a/42237667/1350495

**Comment by tofumatt** [comment]
I definitely still want to restrict with and label; they're both code smells to me and they can be the source of weird bugs.

I personally prefer using array method (eg `array.forEach((element, index) => {` over `for (const index in array) {`) but I suppose the latter is fine. 🤷‍♂️

**Comment by bobsilverberg** [comment]
Thanks @tofumatt. Am I correct that in order to effect this change I would change the [index.js](https://github.com/mozilla/eslint-config-amo/blob/master/index.js) file in this repo? I suppose if we only want to make the change for addons-frontend I could update its [.eslintrc](https://github.com/mozilla/addons-frontend/blob/master/.eslintrc) file instead, but I am assuming we'd want this rule to propagate to all amo repos. What do you think?

**Comment by tofumatt** [comment]
We should definitely always put rules here and have them propagate across repos–that's the point of the shared config. In general I want zero repo-specific rules, and if we do have ones they should be very special-cased and with good reason.
