### ISSUE TITLE
Rename to "addons"

### ISSUE THREAD

**Issue by tofumatt** [mozilla/eslint-config-amo#7]
AMO is a weird, Mozilla-internal designation that is weird and won't make sense to lots of other folks. We don't even call the repos using this "AMO" anymore, it's just a word we say out loud to each other that has crept into our brains as normal when it's really not. 😅 

I know this ruleset is only used by projects largely staffed by Mozilla where we know what "AMO" means but we should rename this to "mozilla-addons" or something like that. It will make the eslint configs that extend it read much nicer than they currently do.

Sure it'll mean an npm/yarn package name change but that's fine the old one will always exist. After `0.1.0` or something it should be `eslint-config-addons`.

**Comment by muffinresearch** [comment]
This project is just for amo related projects. I deliberately called it amo and not addons since this is not the eslint for extensions or Firefox add-ons, and calling it that might be confusing. I don't expect this to be used by any projects outside of those related to amo.

**Comment by tofumatt** [comment]
I guess... no matter what it's confusing. Alright! 😓
